import type { paths } from './schema';

// Minimal typed API client over the generated OpenAPI types.
//
// `./schema.d.ts` is GENERATED by `pnpm gen:api` from the backend's
// /api/docs-json — never hand-write response types (docs/contracts.md ->
// API conventions). This thin fetch wrapper is the only hand-written part; it
// just adds the base URL and JSON parsing. Real data fetching in the panel goes
// through Refine's data provider; this client is for typed ad-hoc calls and to
// prove the generated types compile and are usable.
const baseUrl = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:3000/api';

type HealthResponse =
  paths['/api/health']['get']['responses']['200']['content']['application/json'];

export async function getHealth(): Promise<HealthResponse> {
  const res = await fetch(`${baseUrl}/health`, {
    headers: { Accept: 'application/json' },
  });
  if (!res.ok) {
    throw new Error(`Health check failed: ${res.status}`);
  }
  return (await res.json()) as HealthResponse;
}
